# Generated by Django 5.0.6 on 2024-08-09 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrimage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='overview',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='title',
            new_name='name',
        ),
    ]
