# Generated by Django 5.0.6 on 2024-08-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrimage', '0002_rename_overview_title_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilgrimagelocation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pilgrimagelocation',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
    ]
